### ISSUE TITLE
Error when using modded items on Bukkit API

### ISSUE THREAD

**Issue by Scheggia0** [MohistMC/MohistNeo#24]
Hi, when i try to use custom/modded items in a plugin that uses Bukkit APIs i get this error:

![Image](https://github.com/user-attachments/assets/64ec0450-6599-41e0-8445-90096dd27156)

Another error:

```
[14:18:22 WARN]: Entity task for CrazyCrates v4.0.6 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.SkullMeta.setPlayerProfile(io.papermc.paper.profile.PlayerProfile)'
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.lambda$applyTexture$20(ItemBuilder.java:1695) ~[?:?]
        at TRANSFORMER/neoforge@21.1.180/org.bukkit.inventory.ItemStack.editMeta(ItemStack.java:591) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/org.bukkit.inventory.ItemStack.editMeta(ItemStack.java:570) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.applyTexture(ItemBuilder.java:1680) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.asItemStack(ItemBuilder.java:521) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.asItemStack(ItemBuilder.java:507) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.api.objects.Prize.getDisplayItem(Prize.java:209) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.api.builders.CrateBuilder.getDisplayItem(CrateBuilder.java:372) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.setDisplayItems(CasinoCrate.java:215) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.cycle(CasinoCrate.java:251) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.run(CasinoCrate.java:50) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.util.scheduler.FoliaRunnable.lambda$runAtFixedRate$10(FoliaRunnable.java:247) ~[?:?]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:167) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:114) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:172) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1412) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:370) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1290) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1056) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:330) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[14:18:22 WARN]: Entity task for CrazyCrates v4.0.6 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.SkullMeta.setPlayerProfile(io.papermc.paper.profile.PlayerProfile)'
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.lambda$applyTexture$20(ItemBuilder.java:1695) ~[?:?]
        at TRANSFORMER/neoforge@21.1.180/org.bukkit.inventory.ItemStack.editMeta(ItemStack.java:591) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/org.bukkit.inventory.ItemStack.editMeta(ItemStack.java:570) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.applyTexture(ItemBuilder.java:1680) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.asItemStack(ItemBuilder.java:521) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.asItemStack(ItemBuilder.java:507) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.api.objects.Prize.getDisplayItem(Prize.java:209) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.api.builders.CrateBuilder.getDisplayItem(CrateBuilder.java:372) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.setDisplayItems(CasinoCrate.java:216) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.cycle(CasinoCrate.java:251) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.run(CasinoCrate.java:50) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.util.scheduler.FoliaRunnable.lambda$runAtFixedRate$10(FoliaRunnable.java:247) ~[?:?]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:167) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:114) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:172) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1412) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:370) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1290) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1056) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:330) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[14:18:22 WARN]: Entity task for CrazyCrates v4.0.6 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.SkullMeta.setPlayerProfile(io.papermc.paper.profile.PlayerProfile)'
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.lambda$applyTexture$20(ItemBuilder.java:1695) ~[?:?]
        at TRANSFORMER/neoforge@21.1.180/org.bukkit.inventory.ItemStack.editMeta(ItemStack.java:591) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/org.bukkit.inventory.ItemStack.editMeta(ItemStack.java:570) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.applyTexture(ItemBuilder.java:1680) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.asItemStack(ItemBuilder.java:521) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.asItemStack(ItemBuilder.java:507) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.api.objects.Prize.getDisplayItem(Prize.java:209) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.api.builders.CrateBuilder.getDisplayItem(CrateBuilder.java:372) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.setDisplayItems(CasinoCrate.java:216) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.cycle(CasinoCrate.java:251) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.run(CasinoCrate.java:50) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.util.scheduler.FoliaRunnable.lambda$runAtFixedRate$10(FoliaRunnable.java:247) ~[?:?]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:167) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:114) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:172) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1412) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:370) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1290) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1056) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:330) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[14:18:23 WARN]: Entity task for CrazyCrates v4.0.6 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.SkullMeta.setPlayerProfile(io.papermc.paper.profile.PlayerProfile)'
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.lambda$applyTexture$20(ItemBuilder.java:1695) ~[?:?]
        at TRANSFORMER/neoforge@21.1.180/org.bukkit.inventory.ItemStack.editMeta(ItemStack.java:591) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/org.bukkit.inventory.ItemStack.editMeta(ItemStack.java:570) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.applyTexture(ItemBuilder.java:1680) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.asItemStack(ItemBuilder.java:521) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.asItemStack(ItemBuilder.java:507) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.api.objects.Prize.getDisplayItem(Prize.java:209) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.api.builders.CrateBuilder.getDisplayItem(CrateBuilder.java:372) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.setDisplayItems(CasinoCrate.java:217) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.cycle(CasinoCrate.java:251) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.run(CasinoCrate.java:67) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.util.scheduler.FoliaRunnable.lambda$runAtFixedRate$10(FoliaRunnable.java:247) ~[?:?]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:167) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:114) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:172) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1412) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:370) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1290) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1056) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:330) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[14:18:25 WARN]: Entity task for CrazyCrates v4.0.6 generated an exception
java.lang.NoSuchMethodError: 'void org.bukkit.inventory.meta.SkullMeta.setPlayerProfile(io.papermc.paper.profile.PlayerProfile)'
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.lambda$applyTexture$20(ItemBuilder.java:1695) ~[?:?]
        at TRANSFORMER/neoforge@21.1.180/org.bukkit.inventory.ItemStack.editMeta(ItemStack.java:591) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/org.bukkit.inventory.ItemStack.editMeta(ItemStack.java:570) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.applyTexture(ItemBuilder.java:1680) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.asItemStack(ItemBuilder.java:521) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.api.builders.items.ItemBuilder.asItemStack(ItemBuilder.java:507) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.api.objects.Prize.getDisplayItem(Prize.java:209) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.api.builders.CrateBuilder.getDisplayItem(CrateBuilder.java:372) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.setDisplayItems(CasinoCrate.java:215) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.cycle(CasinoCrate.java:251) ~[?:?]
        at CrazyCrates-4.0.6.jar/com.badbones69.crazycrates.tasks.crates.types.CasinoCrate.run(CasinoCrate.java:67) ~[?:?]
        at CrazyCrates-4.0.6.jar/libs.com.ryderbelserion.vital.paper.util.scheduler.FoliaRunnable.lambda$runAtFixedRate$10(FoliaRunnable.java:247) ~[?:?]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:167) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.scheduler.FoliaEntityScheduler$EntityScheduledTask.accept(FoliaEntityScheduler.java:114) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.180/io.papermc.paper.threadedregions.EntityScheduler.executeTick(EntityScheduler.java:172) ~[neoforge-21.1.180-universal.jar%23240!/:1.21.1]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1412) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:370) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1290) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1056) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:330) ~[server-1.21.1-20240808.144430-srg.jar%23239!/:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
```

**Comment by Mgazul** [comment]
Fixed, waiting for next submission

**Comment by Scheggia0** [comment]
Still not working with the latest version:

```
[14:15:27 ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@71fc08d6, suppressing error
java.lang.ClassCastException: class org.bukkit.craftbukkit.block.CraftBlockEntityState cannot be cast to class org.bukkit.craftbukkit.block.CraftSign (org.bukkit.craftbukkit.block.CraftBlockEntityState and org.bukkit.craftbukkit.block.CraftSign are in module neoforge@21.1.186 of loader 'TRANSFORMER' @121bb45b)
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.block.SignBlock.openTextEdit(SignBlock.java:178) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.SignItem.updateCustomBlockEntityTag(SignItem.java:31) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.BlockItem.place(BlockItem.java:89) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.BlockItem.useOn(BlockItem.java:51) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/neoforge@21.1.186/net.neoforged.neoforge.common.CommonHooks.onPlaceItemIntoWorld(CommonHooks.java:616) ~[neoforge-21.1.186-universal.jar%23238!/:1.21.1]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.item.ItemStack.useOn(ItemStack.java:371) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:464) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1522) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:44) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:10) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1330) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:210) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1312) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1306) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:140) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1278) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1283) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:334) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
        
        
        
        
        
        
        
        
        
        
        
        
[14:26:51 INFO]: [EconomyShopGUI-Premium] [WARN]: A unknown error occurred while loading item: Legno.page6.items.247
[14:26:51 WARN]: java.lang.ClassCastException: class org.bukkit.craftbukkit.block.CraftBlockState cannot be cast to class org.bukkit.craftbukkit.block.CraftBlockEntityState (org.bukkit.craftbukkit.block.CraftBlockState and org.bukkit.craftbukkit.block.CraftBlockEntityState are in module neoforge@21.1.186 of loader 'TRANSFORMER' @32e54a9d)
[14:26:51 WARN]:        at TRANSFORMER/neoforge@21.1.186/org.bukkit.craftbukkit.inventory.CraftMetaBlockState.getBlockState(CraftMetaBlockState.java:263)
[14:26:51 WARN]:        at TRANSFORMER/neoforge@21.1.186/org.bukkit.craftbukkit.inventory.CraftMetaBlockState.<init>(CraftMetaBlockState.java:92)
[14:26:51 WARN]:        at TRANSFORMER/neoforge@21.1.186/org.bukkit.craftbukkit.inventory.CraftItemMetas.lambda$static$34(CraftItemMetas.java:114)
[14:26:51 WARN]:        at TRANSFORMER/neoforge@21.1.186/org.bukkit.craftbukkit.inventory.CraftItemType.getItemMeta(CraftItemType.java:119)
[14:26:51 WARN]:        at TRANSFORMER/neoforge@21.1.186/org.bukkit.craftbukkit.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:400)
[14:26:51 WARN]:        at TRANSFORMER/neoforge@21.1.186/org.bukkit.craftbukkit.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:392)
[14:26:51 WARN]:        at TRANSFORMER/neoforge@21.1.186/org.bukkit.craftbukkit.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:387)
[14:26:51 WARN]:        at TRANSFORMER/neoforge@21.1.186/org.bukkit.craftbukkit.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:382)
[14:26:51 WARN]:        at EconomyShopGUI-Premium-5.25.4.jar//me.gypopo.economyshopgui.objects.ShopItem.<init>(ShopItem.java:228)
[14:26:51 WARN]:        at EconomyShopGUI-Premium-5.25.4.jar//me.gypopo.economyshopgui.objects.shops.types.ShopCategory.loadShopItems(ShopCategory.java:133)
[14:26:51 WARN]:        at EconomyShopGUI-Premium-5.25.4.jar//me.gypopo.economyshopgui.objects.shops.types.ShopCategory.<init>(ShopCategory.java:71)
[14:26:51 WARN]:        at EconomyShopGUI-Premium-5.25.4.jar//me.gypopo.economyshopgui.methodes.StartupReload.loadItems(StartupReload.java:225)
[14:26:51 WARN]:        at EconomyShopGUI-Premium-5.25.4.jar//me.gypopo.economyshopgui.commands.Sreload.execute(Sreload.java:58)
[14:26:51 WARN]:        at TRANSFORMER/neoforge@21.1.186/io.papermc.paper.command.brigadier.bukkit.BukkitCommandNode$BukkitBrigCommand.run(BukkitCommandNode.java:81)
[14:26:51 WARN]:        at TRANSFORMER/neoforge@21.1.186/com.mojang.brigadier.context.ContextChain.runExecutable(ContextChain.java:72)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:29)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.tasks.ExecuteCommand.execute(ExecuteCommand.java:13)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.UnboundEntryAction.lambda$bind$0(UnboundEntryAction.java:8)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.CommandQueueEntry.execute(CommandQueueEntry.java:8)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.execution.ExecutionContext.runCommandQueue(ExecutionContext.java:107)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.Commands.executeCommandInContext(Commands.java:446)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.commands.Commands.performCommand(Commands.java:366)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.performUnsignedChatCommand(ServerGamePacketListenerImpl.java:1791)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$7(ServerGamePacketListenerImpl.java:1765)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1330)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:210)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1312)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1306)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:140)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1278)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1283)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157)
[14:26:51 WARN]:        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:334)
[14:26:51 WARN]:        at java.base/java.lang.Thread.run(Thread.java:1583)
```

And we also have this error with plugins like WorldEdit and WorldGuard:
```
[15:38:39 ERROR]: Could not dispatch event: com.sk89q.worldedit.event.platform.PlayerInputEvent@5945cc72 to handler EventHandler{priority=NORMAL}
java.lang.reflect.InvocationTargetException: null
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:75) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.util.eventbus.EventBus.dispatch(EventBus.java:193) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.util.eventbus.EventBus.post(EventBus.java:181) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.WorldEdit.handleRightClick(WorldEdit.java:645) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.bukkit.WorldEditListener.onPlayerInteract(WorldEditListener.java:136) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor5.execute(Unknown Source) ~[?:?]
        at TRANSFORMER/neoforge@21.1.186/org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[neoforge-21.1.186-universal.jar%23238!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.186/org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[neoforge-21.1.186-universal.jar%23238!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.186/io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:52) ~[neoforge-21.1.186-universal.jar%23238!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.186/io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:130) ~[neoforge-21.1.186-universal.jar%23238!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.186/org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:632) ~[neoforge-21.1.186-universal.jar%23238!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.186/org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:571) ~[neoforge-21.1.186-universal.jar%23238!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.186/org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:533) ~[neoforge-21.1.186-universal.jar%23238!/:1.21.1]
        at TRANSFORMER/neoforge@21.1.186/org.bukkit.craftbukkit.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:529) ~[neoforge-21.1.186-universal.jar%23238!/:1.21.1]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItem(ServerGamePacketListenerImpl.java:1590) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:47) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.game.ServerboundUseItemPacket.handle(ServerboundUseItemPacket.java:9) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:27) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:156) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1330) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:210) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:130) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1312) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1306) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:140) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1278) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1283) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at TRANSFORMER/minecraft@1.21.1/net.minecraft.server.MinecraftServer.lambda$spin$2(MinecraftServer.java:334) ~[server-1.21.1-20240808.144430-srg.jar%23237!/:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NullPointerException
        at MC-BOOTSTRAP/com.google.common@32.1.2-jre/com.google.common.base.Preconditions.checkNotNull(Preconditions.java:903) ~[guava-32.1.2-jre.jar%23172!/:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.blocks.BaseItem.<init>(BaseItem.java:73) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.blocks.BaseItemStack.<init>(BaseItemStack.java:81) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.bukkit.adapter.impl.v1_21.PaperweightAdapter.adapt(PaperweightAdapter.java:669) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.bukkit.BukkitAdapter.adapt(BukkitAdapter.java:517) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.bukkit.BukkitPlayer.getItemInHand(BukkitPlayer.java:83) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.extension.platform.PlayerProxy.getItemInHand(PlayerProxy.java:69) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.extension.platform.PlatformManager.handlePlayerInput(PlatformManager.java:434) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.util.eventbus.MethodHandleEventHandler.dispatch(MethodHandleEventHandler.java:51) ~[?:?]
        at worldedit-bukkit-7.3.9.jar/com.sk89q.worldedit.util.eventbus.EventHandler.handleEvent(EventHandler.java:73) ~[?:?]
        ... 31 more
```

We used the build of last commit **24a1cd3bfcb5de1d06cf64072561687ce66191a0**
